build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  image: git.kpi.fei.tuke.sk:4567/sergej.chodarev/ssh-client
  tags:
    - kpi
  only:
    - main@kpi-zp/2022/dp.pavol.dlugos/redakcny_system_fe
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh sergej@sputnik.kpi.fei.tuke.sk bin/update-service cwem frontend
  variables:
    GIT_STRATEGY: none  # Do not clone repository
